version: "3.9"

services:
  model-service:
    build: ./model-service
    container_name: portfolio-model
    ports:
      - "8000:8000"
    env_file:
      - ./model-service/.env
    depends_on:
      - db
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./model-service:/app

  review:
    build: ./review-service
    container_name: review-service
    ports:
      - "8001:8000"
    env_file:
      - ./review-service/.env
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./review-service:/app

  db:
    image: postgres:15
    container_name: portfolio-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portfolio_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: portfolio-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
