version: "3.9"

services:
  backend:
    build: ./backend
    container_name: portfolio-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: portfolio-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: portfolio_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: portfolio-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
